-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Gép: 127.0.0.1
-- Létrehozás ideje: 2024. Ápr 25. 10:46
-- Kiszolgáló verziója: 10.4.28-MariaDB
-- PHP verzió: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Adatbázis: `elfelejtett`
--
CREATE DATABASE IF NOT EXISTS `elfelejtett` DEFAULT CHARACTER SET utf8 COLLATE utf8_hungarian_ci;
USE `elfelejtett`;

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `chat`
--

CREATE TABLE `chat` (
  `id` int(11) NOT NULL,
  `felhasznalo_id` int(11) NOT NULL,
  `uzenet` longtext NOT NULL,
  `datum` datetime NOT NULL DEFAULT current_timestamp(),
  `kategoria_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

--
-- A tábla adatainak kiíratása `chat`
--

INSERT INTO `chat` (`id`, `felhasznalo_id`, `uzenet`, `datum`, `kategoria_id`) VALUES
(1, 7, 'teszt', '2024-04-12 00:00:00', 0),
(2, 7, 'ujabb Test', '2024-04-12 03:26:10', 0),
(3, 7, 'asdsa', '2024-04-13 14:42:51', 0),
(5, 7, 'asd', '2024-04-17 01:02:00', 1),
(6, 7, 'Tesztelj&uuml;k a kateg&oacute;ri&aacute;kat', '2024-04-17 01:02:15', 1),
(7, 7, 'asasd', '2024-04-17 01:02:46', 0),
(8, 7, 'asd', '2024-04-17 01:02:48', 0);

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `felhasznalok`
--

CREATE TABLE `felhasznalok` (
  `id` int(11) NOT NULL,
  `nev` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `felhasznalonev` varchar(100) NOT NULL,
  `jelszo` varchar(100) NOT NULL,
  `regisztracioDatum` datetime NOT NULL DEFAULT current_timestamp(),
  `profilkep` text NOT NULL DEFAULT 'alap.jpg'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

--
-- A tábla adatainak kiíratása `felhasznalok`
--

INSERT INTO `felhasznalok` (`id`, `nev`, `email`, `felhasznalonev`, `jelszo`, `regisztracioDatum`, `profilkep`) VALUES
(7, 'Test Fiok', 'test@gmail.com', 'vargadavid', 'a1e9d10f3f39612885ace58a44b98a09', '2024-04-12 01:15:09', 'alap.jpg'),
(9, 'Korsós Renáta', 'Valami@gmail.com', 'Renike17', '2008c8f29c376fd5e61b340f3eae7fcd', '2024-04-14 17:54:16', '661f762a45a4f_Profil.png');

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `hozzaszolasok`
--

CREATE TABLE `hozzaszolasok` (
  `id` int(11) NOT NULL,
  `felhasznalo_id` int(11) NOT NULL,
  `konyv_id` int(11) NOT NULL,
  `hozzaszolas` text NOT NULL,
  `datum` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- A tábla adatainak kiíratása `hozzaszolasok`
--

INSERT INTO `hozzaszolasok` (`id`, `felhasznalo_id`, `konyv_id`, `hozzaszolas`, `datum`) VALUES
(30, 7, 1, 'Teszt', '2024-04-13 17:55:29'),
(34, 7, 11, 'teszt', '2024-04-14 11:18:40');

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `kedvelesek`
--

CREATE TABLE `kedvelesek` (
  `id` int(11) NOT NULL,
  `felhasznalo_id` int(11) NOT NULL,
  `konyv_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

--
-- A tábla adatainak kiíratása `kedvelesek`
--

INSERT INTO `kedvelesek` (`id`, `felhasznalo_id`, `konyv_id`) VALUES
(3, 7, 1),
(4, 7, 11),
(6, 8, 14),
(7, 9, 2);

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `konyvek`
--

CREATE TABLE `konyvek` (
  `id` int(11) NOT NULL,
  `oldal_title` text NOT NULL,
  `oldal_video` text NOT NULL,
  `kategoria_id` int(11) NOT NULL,
  `konyv_kep` text NOT NULL,
  `konyv_cim` text NOT NULL,
  `konyv_kiadas` text NOT NULL,
  `iro_nev` text NOT NULL,
  `iro_kep` text NOT NULL,
  `iro_foglalkozas` text NOT NULL,
  `iro_szuletett` text NOT NULL,
  `iro_leiras` text NOT NULL,
  `konyv_leiras` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

--
-- A tábla adatainak kiíratása `konyvek`
--

INSERT INTO `konyvek` (`id`, `oldal_title`, `oldal_video`, `kategoria_id`, `konyv_kep`, `konyv_cim`, `konyv_kiadas`, `iro_nev`, `iro_kep`, `iro_foglalkozas`, `iro_szuletett`, `iro_leiras`, `konyv_leiras`) VALUES
(1, 'Spider-Man: The Amazing Spider-Man', '', 1, 'Kepregeny/amazing185.jpg', 'Spider-Man: The Amazing Spider-Man', '1963', 'Stan Lee', 'Iro/Stan Lee.jpg', 'Képregényíró', '1922-2018', 'Élet és Munka: Stan Lee az amerikai képregényipar legendás alakja volt. A Marvel Comics egyik alapítója és hosszú éveken át a cég írója és szerkesztője volt.\r\nÖrökség: Stan Lee az iparág egyik ikonja és a képregények aranykorának kiemelkedő alakja. Kreativitása, karakteralkotó képessége és hozzáállása mély nyomot hagyott a képregények világában.', 'A \"Spider-Man: The Amazing Spider-Man\" a képregényvilág egyik ikonikus karakterének, Pókembernek a születését tárja elénk. Stan Lee által megalkotott 1963-as kiadásban, ez a történet mély, emberi karakterével és különleges képességeivel vált az olvasók kedvencévé a szuperhősök között.'),
(2, 'Batman: The Dark Knight Returns', '', 1, 'Kepregeny/R.jpg', 'Batman: The Dark Knight Returns', '1986', 'Frank Miller', 'Iro/Frank Miller.jpg', 'Képregényíró', '1957', 'Élet és Munka: Frank Miller egy amerikai képregényíró és rajzoló. Híres az olyan sötét, neonoir és grafikus stílusáról.\r\n            Híres Művei: Miller közismert a \"Batman: Year One\" és a \"The Dark Knight Returns\" című Batman-képregényekért, valamint az \"Elektra: Assassin\" és a \"Sin City\" sorozatokért.\r\n            Örökség: Frank Miller munkássága nagy hatással volt a képregényekre, különösen a szuperhősképregények sötétebb és érettebb irányba való fejlődésében.', 'Frank Miller által írt \'Batman: The Dark Knight Returns\' (1986) a sötét hangulatú, jövőbeli Gotham City-ben játszódó képregény, melyben az öregedő Batman visszatér, hogy szembeszálljon a bűnözéssel, és meghatározó alkotásnak számít a szuperhős műfajban.'),
(3, 'X-Men: The Dark Phoenix Saga', '', 1, 'Kepregeny/R.png', 'X-Men: The Dark Phoenix Saga', '1980-1981', 'Chris Claremont', 'Iro/Chris Claremont.jpg', 'Képregényíró', '1950', 'Élet és Munka: Chris Claremont amerikai képregényíró, aki hosszú időn keresztül dolgozott az X-Men sorozaton.\r\n            Híres Művei: Claremont nevéhez fűződik az \"X-Men\" sorozat újjáélesztése az 1970-es és 1980-as években, és olyan történetek, mint a \"Dark Phoenix Saga\" és a \"Days of Future Past.\"\r\n            Örökség: Claremont a képregények történetmesélésében játszott szerepével és karakterfejlesztéseivel emelkedik ki.', 'Chris Claremont által írt \'X-Men: The Dark Phoenix Saga\' (1980-1981) a mutáns szuperhősök epikus története, melyben Jean Grey erőteljes pszichikai képességei veszélyes mértékben fejlődnek, és a sötét erővel, a Phoenix-kel való találkozása drámai események láncolatát indítja el, az X-Men csapatát sorskérdések elé állítva'),
(4, 'The Avengers: The Kree-Skrull War', '', 1, 'Kepregeny/OIP.jpg', 'The Avengers: The Kree-Skrull War', '1971-1972', 'Roy Thomas', 'Iro/Roy Thomas.jpg', 'Képregényíró', '1940', 'Élet és Munka: Roy Thomas  amerikai képregényíró és szerkesztő. Az iparágban hosszú és jelentős karrierrel rendelkezik.\r\n                Híres Művei: Thomas a Marvelnél dolgozott, és ott töltötte be Stan Lee helyét, amikor az elhagyta az írói pozíciót. Olyan karakterekkel dolgozott, mint a \"Conan the Barbarian,\" \"X-Men,\" \"Avengers\" és \"The Amazing Spider-Man.\"\r\n                Örökség: Roy Thomas jelentős szerepet játszott a képregényipar történetében, és nevéhez fűződik a képregények aranykorának egyik meghatározó időszaka.', 'Roy Thomas által írt \'The Avengers: The Kree-Skrull War\' (1971-1972) az Avengers csapatát az űrbéli konfliktus közepébe vezeti, ahol a Kree és Skrull fajok háborúja a Földre is kihat, létrehozva egy epikus, bonyolult szuperhősképregényt, mely a Marvel-univerzum alapköve lett.'),
(5, 'Deadpool: The Complete Collection', '', 1, 'Kepregeny/R (3).jpg', 'Deadpool: The Complete Collection', '1997-1998', 'Joe Kelly', 'Iro/Joe Kelly.jpg', 'Képregényíró', '1971', 'Élet és Munka: Joe Kelly amerikai képregényíró és filmforgatókönyvíró. Kelly a kilencvenes évek elején kezdett el dolgozni a képregényiparban.\r\n            Híres Művei: Kelly a \"Deadpool\" karakterért vált ismertté, és részt vett az \"Amazing Spider-Man\" sorozat írásában. \r\n            Emellett alkotója volt a \"JLA\" sorozatnak és olyan történeteknek, mint az \"Action Comics\" \"What\'s So Funny About Truth, Justice & the American Way?\" (Ami olyan vicces a igazságban, az igazság, az amerikai mód).', 'Joe Kelly által írt \'Deadpool: The Complete Collection\' (1997-1998) a Deadpool karakter kultikus korszakát öleli fel, amelyben a humor és akció tökéletes egyensúlyban találkozik. A képregény teljes gyűjteménye hűen tükrözi a karakter fekete humorát és különleges anti-hős dinamikáját'),
(6, 'Justice League: The New Frontier', '', 1, 'Kepregeny/R (6).jpg', 'Justice League: The New Frontier', '2004-2005', 'Darwyn Cooke', 'Iro/Darwyn Cooke.jpg', 'Képregényíró', '1962-2016', 'Élet és Munka: Darwyn Cooke kanadai képregényrajzoló és író, aki a szakma meghatározó alakja volt.\r\n            Híres Művei: Cooke a \"DC: The New Frontier\" alkotója, amely egy újragondolt eredettörténeteket mutat be a DC Comics karaktereiről. Rajzolta és írta az \"The Spirit\" sorozatot is.\r\n            Örökség: Darwyn Cooke munkássága a képregényrajzolás különféle műfajaiban', 'Darwyn Cooke által írt \'Justice League: The New Frontier\' (2004-2005) egy stílusos és vizuálisan lenyűgöző képregény, amely a hidegháborús időszakban helyezkedik el, és bemutatja a szuperhősök, köztük a Justice League, újraegyesülését az igazság és szabadság védelmében, miközben mélyebb társadalmi és politikai kihívásokkal néznek szembe'),
(7, 'Superman: Birthright', '', 1, 'Kepregeny/R (2).jpg', 'Superman: Birthright', '2003', 'Mark Waid', 'Iro/Mark Waid.jpg', 'Képregényíró', '1962', 'Élet és Munka: Mark Waid  amerikai képregényíró, aki a Marvel és a DC Comics számára is dolgozott.\r\n            Híres Művei: Waid híres a \"Kingdom Come\" és a \"The Flash\" sorozatokért, valamint az \"Irredeemable\" és az \"Empire\" című műveiért.\r\n            Örökség: Mark Waid munkássága a karakterfejlesztés és a mély történetmesélés terén ért el kiemelkedő sikereket.', 'Mark Waid által írt \'Superman: Birthright\' (2003) modern megközelítésben mutatja be a Kryptonról érkező hőst, Superman születését és felemelkedését, egy olyan történettel, ami az ikonikus karakter eredetét újraértelmezi és izgalmasan bemutatja a két világ közötti belső konfliktusait.'),
(8, 'Thor: The Mighty Thor', '', 1, 'Kepregeny/R (4).jpg', 'Thor: The Mighty Thor', '1983-1987', 'Walter Simonson', 'Iro/Walter Simonson.jpg', 'Képregényíró', '1946', 'Élet és Munka: Walter Simonson  amerikai képregényrajzoló és író. Hosszú pályafutása során sok népszerű karakterrel dolgozott.\r\n            Híres Művei: Simonson a \"Thor\" sorozatban érte el kiemelkedő sikereket, és kiemelkedő rajzait és történeteit az \"X-Factor\" és más Marvel címeken ismerték el. Íróként is dolgozott, például az \"Orion\" és a \"Fantastic Four\" sorozatokban.\r\n            Örökség: Walter Simonson számottevő a képregényrajzolás és -írás terén egyaránt, és a \"Thor\" sorozatát sokan a karakter egyik legkiemelkedőbb korszakaként értékelik.', 'Walter Simonson által írt \'Thor: The Mighty Thor\' (1983-1987) az asgardi isten epikus korszakát örökíti meg, bemutatva Thor hősi küzdelmeit, mitológiai mélységeit és karakterfejlődését egy olyan történetvonalban, amely méltóképpen emelte a szuperhősképregény műfaját.'),
(9, 'The Walking Dead', '', 1, 'Kepregeny/R (5).jpg', 'The Walking Dead', '2003-2019', 'Robert Kirkman', 'Iro/Robert Kirkman.jpg', 'Képregényíró', '1978', 'Élet és Munka: Robert Kirkman amerikai képregényíró, aki ismert a független képregények terén elért sikereiről.\r\n            Híres Művei: Kirkman a \"The Walking Dead\" alkotója, amely hatalmas siker lett, és a zombis apokalipszist mutatja be. Emellett olyan művekhez is hozzájárult, mint az \"Invincible\" és az \"Outcast.\"\r\n            Örökség: Robert Kirkman szerepe különleges, mivel a független képregények világában elért sikerei, mint a \"The Walking Dead,\" megmutatták, hogy a nagy kiadókon kívül is lehet sikeresen működni.', 'Robert Kirkman által írt \'The Walking Dead\' (2003-2019) egy lenyűgöző zombiapokalipszis történet, mely nem csak a túlélésről szól, hanem az emberi kapcsolatok és erkölcsi dilemmák mély és hátborzongató feldolgozását is nyújtja, és az egyik leghosszabb ideig futó és népszerű képregénysorozat lett.'),
(10, 'Wonder Womant', '', 1, 'Kepregeny/R (1).jpg', 'Wonder Womant', '1987', 'George Pérez', 'Iro/Perez.jpg', 'Képregényíró', '1954', 'Élet és Munka: George Pérez  portorikói származású amerikai képregényrajzoló és író.\r\n            Híres Művei: Pérez olyan karaktereket rajzolt, mint a Wonder Woman és a Teen Titans, és kiemelkedő munkát végzett az \"Infinity Gauntlet\" című történetben is.\r\n            Örökség: Pérez gazdag és sokoldalú karriert futott be a képregényiparban, és munkássága hozzájárult a képregényrajzolás különböző aspektusainak fejlődéséhez.', 'George Pérez által írt \'Wonder Woman: The Legend of Wonder Woman\' (1987) a kiválóan megírt és lenyűgözően illusztrált képregény, mely a csodálatos hercegnő eredettörténetét és kalandjait mutatja be, mélyítve karakterét és gazdagítva az Amazonok világát'),
(11, 'Beautiful Disaster', '', 3, 'Erotika/Beautiful.jpg', 'Beautiful Disaster', '2011', 'Jamie McGuire', 'Iro/Jamie McGuire.jpg', 'Regényírónő', '1978', 'Beautiful Disaster Jamie McGuire-tól egy szenvedélyes és drámai romantikus regény, amely 2011-ben jelent meg. A történet középpontjában Abby Abernathy, az elkötelezett diák áll, aki a nyugodt élet és a siker felé tart az egyetemen. Azonban minden megváltozik, amikor beleveti magát a helyi \"vadfiú\", Travis Maddox világába.', 'Beautiful Disaster Jamie McGuire-tól egy szenvedélyes és drámai romantikus regény, amely 2011-ben jelent meg. A történet középpontjában Abby Abernathy, az elkötelezett diák áll, aki a nyugodt élet és a siker felé tart az egyetemen. Azonban minden megváltozik, amikor beleveti magát a helyi \"vadfiú\", Travis Maddox világába.'),
(12, 'A Game of Thrones (A Trónok Harca)', '', 2, 'Fantasykonyv/sarkany.jpg', 'A Game of Thrones (A Trónok Harca)', '1996', ' George R.R. Martin', 'Iro/George R.R. Martin.jpg', 'Amerikai író, forgatókönyvíró.', '1948', 'George Raymond Richard Martin, röviden George R.R. Martin, egy amerikai író, aki elsősorban fantasztikus irodalommal, különösen a \"Trónok harca\" című regénysorozatával vált világhírűvé. Martin azonban nemcsak regényeket írt, hanem televíziós sorozatok, forgatókönyvek és novellák szerzője is.', 'George R.R. Martin bestseller fantasy regénysorozatának első kötete, amelyben politikai intrikák, hatalmi harcok és káprázatos karakterek kavarognak a Westeros kontinensen. A könyv egy lenyűgöző és gyakran váratlan eseménysorozatot kínál az olvasóknak a trónért folytatott küzdelem közepette.'),
(13, 'Assassin\'s Apprentice (Az árnyék mestere)', '', 2, 'Fantasykonyv/assassins.jpg', 'Assassin\'s Apprentice (Az árnyék mestere)', '1995', 'Robin Hobb ', 'Iro/Robin Hobb.jpg', 'Író', '1952', 'Margaret Astrid Lindholm Ogden, azaz a Robin Hobb néven ismert fantasy író. Robin Hobb az irodalomban használt álnév, amit Margaret Astrid Lindholm Ogden, röviden Margaret Ogden, egy amerikai fantasy és tudományos-fantasztikus író használ. \r\nHobb a fantasy műfaj egyik elismert alakja, és számos népszerű regényt írt, amelyek a rajongók körében széles körben elismertek.', 'Robin Hobb fantasy regénye, melyben Fitz, az illegitim trónörökös a királyi udvarban képezik ki, hogy az udvari intrikák és politikai játszmák világában megfeleljen, miközben titokzatos képességeire ébred. Hobb mély karaktereket és összetett világot teremt, ahol az árnyakban dolgozó mesteremberek és a politikai háborúk izgalmasan fonódnak össze.'),
(14, 'Harry Potter and the Philosopher\'s Stone\" (Harry Potter és a Bölcsek Köve)', '', 2, 'Fantasykonyv/harry.jpg', 'Harry Potter and the Philosopher\'s Stone\" (Harry Potter és a Bölcsek Köve)', '1997', 'J.K. Rowling', 'Iro/J.K. Rowling.jpg', 'Író', '1965', 'J.K. Rowling (J.K. az írói név rövidítése a \"Joanne Rowling\" nevéből, amelyet az író tényleges nevének kezdeti betűire alkotott) egy brit írónő, aki a világhírű \"Harry Potter\" sorozatán keresztül vált az egyik legismertebb és legsikeresebb szerzővé. Rowlingnak azonban más művei is vannak, és az \"Robert Galbraith\" írói álnéven is írt detektívregényeket.\r\nJ.K. Rowling az irodalmon kívül ismert a karitatív tevékenységeiről és az aktivizmusáról. A Harry Potter sorozat jelentős kulturális hatással bír, és világszerte milliók szeretik és olvassák.', 'J.K. Rowling varázslatos világába kalauzol minket, ahol a fiatal varázsló, Harry Potter felfedezi örökségét és részese lesz az iskolai varázslatoknak, barátságoknak, valamint a Sötét Varázsló, Voldemort elleni küzdelemnek. A könyv megteremtette a Harry Potter-sorozat alapját és világhírűvé tette Rowling írónőt.'),
(15, 'The Hobbit', '', 2, 'hobbit.jpg', 'The Hobbit', '1937', 'J.R.R. Tolkien', 'Iro/J.R.R. Tolkien.png', 'Író', '1892', 'J.R.R. Tolkien (John Ronald Reuel Tolkien) angol író, filológus és egyetemi tanár volt, aki a fantasy műfaj egyik legmeghatározóbb alakja. Tolkien a \"Gyűrűk Ura\" trilógiájával vált világszerte ismertté, de munkásságában számos más fontos művet is alkotott. \r\nŐ alkotta meg a középföldei (Middle-earth) mitológiát és nyelveket, amelyek a fantasztikus irodalom későbbi alkotásait is erősen befolyásolták.Tolkien munkássága az irodalomtudomány és a fantasy műfajának kialakításában is mély nyomokat hagyott. \r\nA Nyugati Gyűrűkért (The Lord of the Rings) 1954-ben és 1955-ben elnyerte a Carnegie Medal for Fiction-t, és széles körben elismerték az irodalmi értékeiért, valamint a fantastikus világokba való mély betekintésért. Tolkien 1892. január 3-án született, és 1973. szeptember 2-án hunyt el.', 'A történet középpontjában a hobbit nevű lény, Bilbo Baggins áll, akit egy váratlan kalandra hívnak el tündék és törpök társaságában. A könyv 1937-ben jelent meg, és azóta is klasszikusnak számít a fantasy irodalomban, lenyűgöző világával és izgalmas kalandjaival.'),
(16, 'The Lies of Locke Lamora', '', 2, 'Fantasykonyv/hazugsag.jpg', 'The Lies of Locke Lamora', '2006', 'Scott Lynch', 'Iro/Scott Lynch.jpg', 'Író', '1978', 'Scott Lynch egy amerikai fantasyszerző, aki leginkább a \"Gentleman Bastard\" sorozatáról ismert. A sorozat egy izgalmas és intrikákkal teli világot mutat be, és a tolvajokról és csalókról szóló történeteiben gazdag karakterek és fordulatok találhatók.\r\nScott Lynch azonban nehezen tartja a kiadási határidőket, és a sorozat következő részei hosszú időn keresztül nem jelentek meg. Az író a rajongóival való nyílt kommunikációval és a kihívásokkal szembeni nyílt őszinteségével vált ismertté azokkal a nehézségekkel kapcsolatban, amelyekkel a magánéletében és a szakmai életében szembesült. \r\nA rajongók várják a folytatást és reménykednek abban, hogy Lynch befejezi a sorozatot.', 'Scott Lynch kalandos fantasy regénye, melyben a mesteri csaló, Locke Lamora és társai a Velencei-stílusú Camorr városában hajtanak végre bonyolult lopásokat. A könyv izgalmas intrikákat, lenyűgöző karaktereket és káprázatos világépítést kínál, egy olyan városban, ahol a bűn, a politika és a művészet találkozik. '),
(17, 'Mistborn: The Final Empire', '', 2, 'Fantasykonyv/ssd.jpg', 'Mistborn: The Final Empire', '2006', 'Brandon Sanderson', 'Iro/Brandon Sanderson.jpg', 'Író', '1975', 'Brandon Sanderson egy amerikai fantasyszerző, aki számos népszerű fantasy regénnyel és sorozattal vált ismertté. Ő a \"Kosmere\" nevű világépítési projekt résztvevője is, amely több könyvsorozatot is magában foglal. Sanderson híres a komplex világépítéséről, az eredeti varázslatrendszereiről és a karakterei mély kidolgozottságáról.\r\nBrandon Sanderson a fantasy műfajának egyik jelenlegi vezető alakja, és elkötelezett a rajongóival való kapcsolattartásban. A Kosmere-projekt keretében írt sorozatok összekapcsolódnak, és egy közös mitológiát és történetet alkotnak.', 'Brandon Sanderson izgalmas fantasy regénye, ahol egy elnyomott társadalomban, ahol a sötét hatalmak uralkodnak, egy fiatal lány, Vin megtanulja használni a mistborn képességeit, és részese lesz egy forradalomnak, hogy megtörje a hatalom láncolatait. Sanderson egyedi világépítése és karakterfejlődése teszi ezt a regényt emlékezetessé a fantasy rajongók számára.'),
(18, 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', '', 2, 'Fantasykonyv/narnia.jpg', 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', '1950', 'C.S. Lewis', 'Iro/C.S. Lewis.jpg', 'Író', '1898', 'C.S. Lewis, teljes nevén Clive Staples Lewis, angol író, irodalomkritikus és egyetemi tanár volt. Lewis a 20. század egyik legkiemelkedőbb irodalmi alakja, és leginkább a Narnia Krónikák című gyerekkönyvsorozatával vált ismertté. \r\nŐ írta továbbá népszerű apologetikus műveket és irodalomkritikai esszéket.C.S. Lewis 1898. november 29-én született Belfastban, Észak-Írorságban, és 1963. november 22-én halt meg.', 'C.S. Lewis klasszikus regénye, melyben négy testvér egy varázslatos világba, Narniába kerül, ahol egy gonosz boszorkány uralma alatt álló birodalom és az erőteljes Aslan, az oroszlán közötti küzdelmet élhetjük át. Lewis lenyűgözően mesél, és a történet mélyebb rétegeiben morális és filozófiai témákat feszeget, miközben elkalauzol minket a varázslatos Narnia birodalmába.'),
(19, 'The Fellowship of the Ring', '', 2, 'Fantasykonyv/ring.jpg', 'The Fellowship of the Ring', '1954', 'J.R.R. Tolkien', 'Iro/J.R.R. Tolkien.png', 'Író', '1892', 'J.R.R. Tolkien (John Ronald Reuel Tolkien) angol író, filológus és egyetemi tanár volt, aki a fantasy műfaj egyik legmeghatározóbb alakja. Tolkien a \"Gyűrűk Ura\" trilógiájával vált világszerte ismertté, de munkásságában számos más fontos művet is alkotott. \r\nŐ alkotta meg a középföldei (Middle-earth) mitológiát és nyelveket, amelyek a fantasztikus irodalom későbbi alkotásait is erősen befolyásolták.Tolkien munkássága az irodalomtudomány és a fantasy műfajának kialakításában is mély nyomokat hagyott. \r\nA Nyugati Gyűrűkért (The Lord of the Rings) 1954-ben és 1955-ben elnyerte a Carnegie Medal for Fiction-t, és széles körben elismerték az irodalmi értékeiért, valamint a fantastikus világokba való mély betekintésért. Tolkien 1892. január 3-án született, és 1973. szeptember 2-án hunyt el.', 'J.R.R. Tolkien legendás regénye, melyben a kis hobbit, Frodo Baggins és társai egy veszélyes küldetésre indulnak, hogy megsemmisítsék a Gonosz Gyűrűjét. A könyv lenyűgöző világa, mély karakterei és izgalmas kalandjai a fantasy irodalom kiemelkedő alkotásává teszik, és elindítják a \"Gyűrűk Ura\" epikus trilógiát.'),
(20, 'Good Omens (Jóslatok könyve)', '', 2, 'Fantasykonyv/isten.jpg', 'Good Omens (Jóslatok könyve)', '1990', 'Terry Pratchett és Neil Gaiman', 'Iro/joslat1.jpg\r\n', 'Író', '1948', 'Angol író, aki a Discworld című sorozatával vált ismertté. A Discworld egy humoros fantasy világ, amelyet egy lapos, korong alakú világ és négy elefánt hordoz. \r\nPratchett művei gyakran tartalmaznak szatirikus elemeket, kritikát a valóságra és az abszurditásra való figyelmet.', 'Neil Gaiman és Terry Pratchett együttműködéséből született humoros fantasy regény, melyben egy angyal és egy démon, akik megszerették a Földet, összefognak, hogy megakadályozzák az apokalipszist, ám a dolgok nem mennek mindig a tervezett úton. A könyv szellemes narratívája és egyedi karakterei a fantasy és humor kedvelőinek egyaránt szórakoztató élményt nyújtanak.'),
(21, 'The Name of the Wind (A Szél Neve)', '', 2, 'Fantasykonyv/szel.jpg', 'The Name of the Wind (A Szél Neve)', '2007', 'Patrick Rothfuss', 'Iro/Patrick Rothfuss.jpg', 'Író', '1973', 'Patrick Rothfuss egy amerikai fantasyszerző, aki a \"Királygyilkos Krónikái\" trilógiájáról vált ismertté. Rothfuss az írás mellett egyetemi oktatóként is tevékenykedik.Patrick Rothfussnak azonban még mindkét trilógia befejező része kiadatlan. \r\nAz író többször elhalasztotta a trilógia harmadik kötetének, a \"The Doors of Stone\"-nak a megjelenését, és a rajongók várták és várják az évek óta. Az író továbbá részt vesz különböző jótékonysági kezdeményezésekben és az irodalmi közösségekben is aktív.\r\n            A \"Királygyilkos Krónikái\" Rothfuss első fantasy regényei, de a szerző egyedi stílusa és karakterei hamar elnyerték a fantasy rajongók tetszését. Munkásságát méltatják a világépítés, a karakterfejlődés és az íráskészség terén.', 'Patrick Rothfuss epikus fantasy regénye, melyben Kvothe, a tehetséges zenei tehetségű és varázsló irányítja visszaemlékezéseit, elmesélve életének különleges és veszélyes eseményeit. Rothfuss lenyűgözően írja le ezt a lenyűgöző és gazdag világot, miközben Kvothe kalandjai a rejtélyek, szerelmek és varázslatok labirintusába vezetik az olvasót.'),
(22, 'Belle de Jour', '', 3, 'Erotika/OIP (2).jpg', 'Belle de Jour', '1928', 'Joseph Kessel', 'Iro/Joseph Kessel.jpg', 'Francia újságíró és író', '1898', 'Aki különböző műfajokban alkotott, beleértve a regényeket, esszéket és újságcikkeket.\r\nHíres Művei: Kessel nevéhez fűződik az \"Army of Shadows\" (Árnyak hadserege) című regény, amely a francia ellenállás hőseit mutatja be a második világháború alatt.', '\"Belle de Jour\" Joseph Kessel tollából egy 1928-as kiadású provokatív regény, amely egy nő életét meséli el, aki napközben egy magas társadalmi státuszú prostituált, miközben esténként egy másik életet él. Kessel műve mesterien keveri az erotikát és a társadalomkritikát, hozzájárulva az irodalmi kánonhoz a 20. században.'),
(23, 'Little Birds', '', 3, 'Erotika/Little_Birds_Nin.jpg', 'Little Birds', '1979', 'Anaïs Nin', 'Iro/Anais Nin.jpg', 'Francia-kubai író és naplóíró', '1903', 'A 20. századi erotikus irodalom egyik fontos alakja volt.\r\nHíres Művei: Nin a \"Delta of Venus\" és a \"Little Birds\" című erotikus novellái miatt vált ismertté. Naplóíróként is ismert a személyes élményeiről szóló naplóiról.', 'Little Birds\" (Kis madarak) Anaïs Nin egyik erotikus irodalmi műve, amely 1979-ben jelent meg. Az írónő ismert volt szenvedélyes és kifinomult stílusáról, és ebben a gyűjteményben is az emberi szexualitás, vágy és szerelem témáját feszegeti.'),
(24, 'Fifty Shades of Grey', '', 3, 'Erotika/R.jpg', 'Fifty Shades of Grey', '2011', 'E.L. James', 'Iro/James.webp', 'Író', '1963', 'Élet és Munka: Erika Leonard James, ismertebb írói nevén E.L. James, brit írónő, aki világhírűvé vált a \"Fifty Shades of Grey\" trilógiával.\r\nHíres Művei: James a \"Fifty Shades of Grey,\" \"Fifty Shades Darker\" és \"Fifty Shades Freed\" regények szerzője, amelyek a romantikus és erotikus műfajban váltak rendkívül sikeresekké.', 'E.L. James által írt \'Fifty Shades of Grey\' (2011) egy szenvedélyes és kontroverz romantikus regény, mely a fiatal irodalmi szerkesztő, Anastasia Steele és a gazdag üzletember, Christian Grey közötti erotikus és összetett kapcsolatot mutatja be. A mű jelentős vitákat keltett, miközben a BDSM-témájú romantikus irodalom egyik kiemelkedő példája lett.'),
(25, 'Haunting Adeline - Kísérteni Adeline-t', '', 3, 'Erotika/R (4).jpg', 'Haunting Adeline - Kísérteni Adeline-t', '2023', 'H.D. Carlton', 'Iro/H.D. Carlton.jpg', 'Író', '1996', 'Élet és Munka: H.D. Carlton egy erotikus műveket író szerző, aki a romantika és a szenvedély témájában alkot.\r\nHíres Művei: Carlton népszerű az erotikus regényeiről, amelyekben kiemelt szerepet kapnak a szenvedélyes kapcsolatok és az érzelmi elemek.', 'Befolyásolom bárki érzelmeit, aki csak engedi. Fájdalmat okozok, megríkatom, megnevettetem és sóhajtásra késztetem. De a szavaim leperegnek róla. Főleg akkor, amikor könyörögve kérem, hogy távozzon. Mindig jelen van, figyel és vár. És én sosem tudom...'),
(26, 'Icebreaker - Jégtörő', '', 3, 'Erotika/10224806_4.jpg', 'Icebreaker - Jégtörő', '2023', 'Hannah Grace', 'Iro/Hannah Grace.jpg', 'Írónő', '1987', 'Élet és Munka: Hannah Grace egy írónő, aki elsősorban romantikus és erotika műveket alkot.\r\nHíres Művei: Íróként Grace népszerű a romantikus és szenvedélyes történeteiért. Az írónő gyakran foglalkozik a szerelem és a kapcsolatok különböző aspektusaival.', 'Anastasia Allen egész életében azért dolgozott, hogy bekerülhessen az USA olimpiai csapatába. Ötéves kora óta versenyszerűen műkorcsolyázik, teljes egyetemi ösztöndíjjal büszkélkedhet, hála helyének a Maple Hills egyetem korcsolyacsapatában, és olyan az időbeosztása, hogy..'),
(27, 'A láncok mögött - Tetováltak 3.', '', 3, 'Erotika/lanc.jpg', 'A láncok mögött - Tetováltak 3.', '2023', 'Meghan March', 'Iro/Meghan March.webp', 'Szerzőnő', '-', 'Élet és Munka: Meghan March egy amerikai romantikus és erotika szerző, aki ismert a New York Times bestseller listára került műveiről.\r\nHíres Művei: March olyan könyveiről ismert, mint a \"Beneath\" sorozat és a \"Dirty Billionaire\" trilógia. A műveiben gyakran fellelhetők az érzelmek, a szenvedély és a romantika elemi.', 'Lord Robichaux vagyok, és az utcán nőttem fel, úgyhogy tudom, hogy soha semmi nem annyira egyszerű, mint amilyennek látszik - főleg most nem, amikor ez a gazdag lány, Eleanor Snyder állást követel a zálogházamban.\r\n Ő a legcsábítóbb nő, akit valaha láttam, így átkozott legyek, ha elengedem.\r\nMinden olyan bonyolult, de ha róla van szó, még ezt sem bánom. Mindkettőnknek megvannak a küzdelmei, és csak akkor lehet közös jövőnk, ha a múltat magunk mögött tudjuk hagyni.\r\nVajon lesz elég erőnk letépni a láncokat?'),
(28, 'The Story of the Eye (A szem története)', '', 3, 'Erotika/story-of-the-eye-book_2102.jpg', 'The Story of the Eye (A szem története)', '1928', 'Georges Bataille', 'Iro/Georges Bataille.jpg', 'Francia író és filozófus', '1897', 'A 20. század elején és közepén élt. Munkásságában széles spektrumú témákat érintett, beleértve az erotika és a szexualitás elemzését is.\r\nHíres Művei: Bataille művei közé tartozik az \"Erotism: Death and Sensuality\" (Erotika: Halál és Érzékiesség), amelyben az erotikus élmények és az élet és halál kapcsolatát vizsgálja.', 'The Story of the Eye\" (A szem története) Georges Bataille tollából 1928-ban megjelent provokatív és sokat vitatott regény. A mű erotikával, szürreális elemekkel és tabudöntögetéssel átitatott, melyben Bataille merész és kísérletező stílusban kutatja az emberi szexualitás sötét és különös szegmenseit, létrehozva egy feledhetetlen és sokszor zavarba ejtő olvasói élményt.'),
(29, 'A csók (The Kiss)', '', 3, 'Erotika/The_Kiss_(memoir).jpg', 'A csók (The Kiss)', '1977', 'Kathryn Harrison', 'Iro/Kathryn Harrison.jpg', 'Író', '1961', 'Élet és Munka: Kathryn Harrison egy amerikai író és memoárista, aki a szépirodalomban és életrajzi műfajokban is alkot.\r\nHíres Művei: Harrison olyan műveiről ismert, mint a \"The Kiss\" (A csók), amely egy személyes memoár a családi traumákról és az érzelmekről.', 'A csók\" (The Kiss) Kathryn Harrison tollából, 1997-ben megjelent memoár, amelyben az írónő őszintén és merészen beszél saját élményéről, egy tabutémáról: saját apjával folytatott zaklató viszonyáról. A regény megdöbbentő őszinteséggel vizsgálja az összetett emberi kapcsolatokat és a tabudöntögető témákat, hozzájárulva a személyes tapasztalatok és az irodalom határterületén való felfedezéshez.'),
(30, 'Story of O ', '', 3, 'Erotika/R (1).jpg', 'Story of O ', '1954', 'Pauline Réage', 'Iro/Pauline.jpg', 'Francia újságíró és regényíró', '1907', 'Élet és Munka: Pauline Réage a pseudonim, amelyet Dominique Aury használt a \"Story of O\" (O története) című híres erotikus regénye alatt. Aury francia író és könyvtáros volt.\r\nHíres Művei: Aury \"Story of O\"-ja egy mély, szenvedélyes és provokatív regény, amely az erotikus irodalom egyik jelentős alkotása lett.', ' A \"Story of O\" (O története) egy provokatív és kihívó erotikus regény, amit Pauline Réage írt. Az 1954-es kiadásában bemutatott történet tabudöntögető stílusával és mélyebb érzelmi rétegeivel emelkedik ki, hozzájárulva az erotikus irodalom megújításához és felfrissítéséhez.'),
(31, 'Gone with the Wind', '', 4, 'Romantika/efutaszel.jpg', 'Gone with the Wind', '1936', 'Margaret Mitchell', 'Iro/Margaret Mitchell.jpg', 'Író', '1900', 'Margaret Mitchell az amerikai író, aki leginkább Az Eredetiben (Gone with the Wind) című regényéről ismert. \r\nA regény 1936-ban jelent meg, és azonnal hatalmas sikert aratott. \r\nA történet az amerikai polgárháború és az azt követő rekonstrukciós időszak idején játszódik, és a déli életmódot és kultúrát ábrázolja. \r\nMitchell 1937-ben Pulitzer-díjat kapott a regényért.', 'Margaret Mitchell \"Gone with the Wind\" egy epikus regény az amerikai polgárháború idején. Scarlett O\'Hara karaktere az északi és déli konfliktus közepette próbálja megőrizni déli birtokát, és közben keresi a szerelem és boldogság értelmét.'),
(32, 'Wuthering Heights ', '', 4, 'Romantika/heights.jpg', 'Wuthering Heights ', '1847', 'Emily Brontë', 'Iro/Emily.webp', 'Író', '1818', ' Emily Brontë angol írónő volt, és leginkább az egyetlen regényével, a \"Üvöltő szelek\" (\"Wuthering Heights\") című művével vált ismertté. Ő és testvérei, Charlotte és Anne Brontë, mindhárman jelentős írók voltak a 19. században.', 'Emily Brontë \"Wuthering Heights\" egy sötét és szenvedélyes szerelmi történetet mesél el Cathy és Heathcliff között. A Yorkshire-i mocsaras vidéken játszódó regényben az erős érzelmek, családi titkok és a tragédia motívumai szövik át a történetet.'),
(33, 'Jane Eyre', '', 4, 'Romantika/eye.jpg', 'Jane Eyre', '1847', 'Charlotte Brontë', 'Iro/Charlotte.jpg', 'Író', '1816', 'Charlotte Brontë angol írónő, a Brontë testvérek közül a legidősebb. Ő is nagyon jelentős író volt a 19. századi angol irodalomban. Legismertebb műve a \"Jane Eyre\", ami egyik legfontosabb angol regények egyike, és a világirodalom kiemelkedő alkotásaként tartják számon.', 'Charlotte Brontë regénye, a \"Jane Eyre,\" egy kihívásokkal teli életút története. Jane, a fiatal árva lány, nevelőnővé válik a titokzatos Mr. Rochester házában. A történet tele van romantikával és drámával, miközben Jane próbálja megtalálni helyét a világban és kibontakoztatni az önállóságát. '),
(34, 'Me Before You', '', 4, 'Romantika/beforeyou.jpg', 'Me Before You', '2012', 'Jojo Moyes', 'Iro/Jojo Moyes.jpg', 'Író', '1969', 'Jojo Moyes egy brit író, aki különböző műfajokban alkot, beleértve a romantikus regényeket és a drámákat is. \r\nAz egyik legsikeresebb műve a „Me Before You” című regény, ami később filmet is kapott.', 'Jojo Moyes \"Me Before You\" egy érzelmes történet egy fiatal nőről, Lou-ról, aki váratlanul kap munkát egy baleset következtében mozgássérült férfi, Will gondozójaként. A történet során Lou és Will között kialakuló kapcsolat mély érzelmekre és életfilozófiára reflektál.'),
(35, 'The Notebook', '', 4, 'Romantika/Notebook.jpg', 'The Notebook', '1996', 'Nicholas Sparks', 'Iro/Nicholas Sparks.jpg', 'Író', '1965', 'Nicholas Sparks amerikai író, aki elsősorban romantikus regényeiről és drámáiról ismert. A témái gyakran az érzelmekre, szerelemre és emberi kapcsolatokra összpontosítanak.', 'Nicholas Sparks \"The Notebook\" egy érzelmekkel teli szerelmi történetet mesél el Noah és Allie között, akiknek kapcsolata próbára lesz téve az élet kihívásaival. Az idősebb Noah visszaemlékezéseiben a szeretet és az emlékezés erőteljes motívumai jelennek meg.'),
(36, 'P.S. I Love You ', '', 4, 'Romantika/szeretlek.jpg', 'P.S. I Love You ', '2004', 'Cecelia Ahern', 'Iro/Cecelia Ahern.jpg', 'Író', '1981', 'Cecelia Ahern ír írónő és forgatókönyvíró. Ahern első regénye, a \"P.S. I Love You\" (2004) hatalmas siker volt, és ez az író karrierjének indítója volt. Ezt a könyvét később sikeresen adaptálták filmre is.', 'Cecelia Ahern \"P.S. I Love You\" egy megható történet a gyászról és a gyógyulásról. Holly, a főszereplő, férje halála után leveleket kap, amelyeket még azelőtt írt neki, mielőtt meghalt. Ezek a levelek segítik Hollyt feldolgozni veszteségét és újra megtalálni önmagát.'),
(37, 'Pride and Prejudice', '', 4, 'Romantika/pride.jpg', 'Pride and Prejudice', '1813', 'Jane Austen', 'Iro/Jane Austen.jpg', 'Író', '1775', 'Jane Austen angol írónő, aki az angol regény egyik legkiemelkedőbb alakja, és a romantika korszakának kiemelkedő írója. Művei a társadalmi élet és a szerelem kifinomult ábrázolásáról ismertek, és ma is rendkívül népszerűek a világon.', 'Jane Austen \"Pride and Prejudice\" című regénye az angol regényirodalom egyik klasszikusa. A történet középpontjában Elizabeth Bennet áll, aki próbálja navigálni a társadalmi elvárások között, miközben kialakul köztük a szerelem a jóképű, de kevéssé megközelíthető Mr. Darcy-vel.'),
(38, 'Sense and Sensibility', '', 4, 'Romantika/sense.jpg', 'Sense and Sensibility', '1811', 'Jane Austen', 'Iro/Jane Austen.jpg\"', 'Író', '1775', 'Jane Austen angol írónő, aki az angol regény egyik legkiemelkedőbb alakja, és a romantika korszakának kiemelkedő írója. Művei a társadalmi élet és a szerelem kifinomult ábrázolásáról ismertek, és ma is rendkívül népszerűek a világon.', 'Jane Austen másik remekműve, a \"Sense and Sensibility,\" két testvér, Elinor és Marianne Dashwood történetét meséli el, akik eltérően közelítik meg az érzelmeket és az életüket. A regény humorral és éles társadalomkritikával ábrázolja az angol társadalom szokásait.'),
(39, 'The Fault in Our Stars', '', 4, 'Romantika/csillagokbanahiba.jpg', 'The Fault in Our Stars', '2012', 'John Green', 'Iro/John Green.jpg', 'Író', '1977', 'John Green amerikai író és videóblog-író. Legismertebb művei közé tartoznak a fiatal felnőttek számára írt regények, amelyek széles körben elismertek és népszerűek lettek fiatal olvasók és felnőttek körében egyaránt.', 'John Green \"The Fault in Our Stars\" egy ifjúsági regény, mely Hazel Grace Lancaster és Augustus Waters történetét meséli el. Mindketten rákbetegséggel küzdenek, és a regény a szeretet, elvesztés és az élet értelmének témáit boncolgatja.'),
(40, 'A vonzás törvénye', '', 4, 'Romantika/vonzas.jpg', 'A vonzás törvénye', '2018', 'Kollár Betti', 'Iro/Betti.jpg', 'Író', '1998', 'Ifjúsági és fiatal felnőtteknek szóló romantikus regények, A vonzás törvénye könyvsorozat és az Álmomban megleltelek című könyv szerzője. Első könyve, A vonzás törvénye 2020-ban elnyerte a Dugonics András Irodalmi Díjat.', 'Serenity édesanyjával egy távoli városba költözik, hogy maguk mögött hagyjanak egy múltbéli tragédiát. A lány a helyi egyetemen folytatja tovább a tanulmányait, és már a beiratkozás napján megismerkedik Ace-szel, aki a kar közismert szívtiprójának hírében áll. Ace rögtön meglátja a kihívást Serében, a lány azonban nem dől be a fiú vonzerejének. Hogy lerázza, alkut ajánl neki: ha Ace egy hónapig mellőzi a többi lányt, megkaphatja őt egy éjszakára. Serének így egyszerre kell szembenéznie a múltjában történt eseményekkel és a fiú iránt érzett egyre növekvő vonzalmával, nem beszélve Rhettről, Ace gúnyos és hűvös legjobb barátjáról, aki a jelek szerint mindig rosszkor van jó helyen. Bár Ace roppant vonzó, úgy tűnik, Serének ez önmagában mégsem elég. Vajon Ace végig csak elcsábítani akarja a lányt, vagy Sere el tudja érni, hogy szép lassan megváltozzon mellette?'),
(41, 'The Adventures of Huckleberry Finn', '', 5, 'Thiller/finn.jpg', 'The Adventures of Huckleberry Finn', '1884', 'Mark Twain (Samuel Langhorne Clemens)', 'Iro/Mark Twain.jpg', 'Író', '1835', 'Mark Twain az amerikai irodalom egyik legismertebb alakja, a Huckleberry Finn kalandjai (The Adventures of Huckleberry Finn) és A Tom Sawyer kalandjai (The Adventures of Tom Sawyer) című regényeiről ismert. \r\n Ő volt az amerikai realista irodalom egyik kiemelkedő alakja, és sokat tett az amerikai dialektusokkal és a humorral teli irodalom fejlesztéséért.', 'Huckleberry Finn, a klasszikus amerikai irodalom egyik leghíresebb karaktere, a Mississippi folyó mentén kalandos utazásra indul Jim, egy rabszolga társával. A regény a déli Egyesült Államok rabszolgaság és társadalmi kérdéseit érinti, és Twain mesterien keveri a humor és kritika elemeket.'),
(42, 'The Da Vinci Code', '', 5, 'Thiller/thedavincicode.jpg', 'The Da Vinci Code', '2003', 'Dan Brown', 'Iro/Dan Brown.jpg', 'Író', '1964', 'Dan Brown amerikai író, aki leginkább A Da Vinci-kód (The Da Vinci Code) című regényéről vált ismertté. \r\nA könyvei rendkívül népszerűek, és gyakran keverik a krimi, a thriller és a vallási témákat.', 'Egy rejtélyes gyilkosság nyomába ered a szimbólumok és rejtélyek szakértője, Robert Langdon, és egy kódfejtő nő, Sophie Neveu. A történet mélyen kapcsolódik a művészettörténethez és vallási titkokhoz, és az oldalakon keresztül pörgő thriller a modern irodalom egyik legnagyobb sikerévé vált.'),
(43, 'Jurassic Park ', '', 5, 'Thiller/dino.jpg', 'Jurassic Park ', '1990', ' Michael Crichton', 'Iro/Michael Crichton.jpg', 'Író', '1942', 'Michael Crichton amerikai író, forgatókönyvíró, filmrendező és producer volt. \r\nŐ volt az Égi szféra (Jurassic Park) és Sokkal több a vadászatnál (The Andromeda Strain) című bestsellerek szerzője. \r\nCrichton a sci-fi és a techno-thriller műfajokban alkotott, és munkásságával jelentős hatást gyakorolt a popkultúrára.', 'Egy gazdag vállalkozó elkészíti saját dinoszaurusz-tematikájú parkját, de a dolgok gyorsan kicsúsznak az ellenőrzés alól, amikor a dinoszauruszok szabadon kezdenek mozogni. Crichton izgalmasan ötvözi a tudományt és a kalandot, miközben az emberi beavatkozás következményeire mutat rá.'),
(44, 'The Adventures of Sherlock Holmes', '', 5, 'Thiller/retekhiresnyomozo.jpg', 'The Adventures of Sherlock Holmes', '1892', 'Arthur Conan Doyle', 'Iro/Arthur Conan Doyle.jpg', 'Író', '1859', 'Arthur Conan Doyle skót író és orvos, aki leginkább Sherlock Holmes detektív történeteiről ismert. \r\nA Sherlock Holmes-széria a bűnügyi irodalom egyik legmeghatározóbb és legismertebb része lett.', 'A Sherlock Holmes kalandjai egy sor rövid történet, amelyekben a zseniális detektív, Sherlock Holmes és hű társa, Dr. John Watson különböző rejtélyeket oldanak meg Londonban. A könyv izgalmas esetek sorát tartalmazza, melyekben Holmes lenyűgöző megfigyelőképessége és logikája kerül előtérbe.'),
(45, 'The Count of Monte Cristo', '', 5, 'Thiller/count.jpg', 'The Count of Monte Cristo', '1844', 'Andre Dumas', 'Iro/Andre Dummas.webp', 'Író', '1802', 'Alexandre Dumas, Alexandre Dumas père, teljes nevén Dumas Davy de la Pailleterie (Villers-Cotterêts, 1802. július 24. – Puys, Dieppe mellett, 1870. december 5.) francia író, legismertebb művei kalandos történelmi regények, amelyek a világ legolvasottabb francia írójává tették őt. Több regényéből (például a Monte Cristo grófja és a D’Artagnan-történetek) készült', 'Edmond Dantès, a fiatal tengerész hamarosan életének poklát éli át, amikor árulás miatt börtönbe kerül. Miután elszökik, Monte Cristo grófként tér vissza, hogy bosszút álljon azokon, akik elárulták őt. Az intrika és kalandok gazdag szövésű regényét Dumas remek karakterábrázolással és fordulatokkal festi meg.'),
(46, 'The Girl with the Dragon Tattoo', '', 5, 'Thiller/Tetko.jpg', 'The Girl with the Dragon Tattoo', '2005', 'Stieg Larsson', 'Iro/Stieg Larsson.jpg', 'Író', '1954', 'Stieg Larsson svéd író, újságíró és politikai aktivista volt. \r\nLeghíresebb műve a Millenium-trilógia, melynek első kötete A lány, aki a tűzzel játszik (The Girl with the Dragon Tattoo) világszerte hatalmas sikert aratott. \r\nLarsson a trilógia befejezése előtt, 2004-ben hunyt el, így sosem élhette meg munkája globális sikereit.', 'Stieg Larsson regénye a Millennium-trilógia első része, és egy bonyolult krimi, amelyben a gazdag iparmágnás unokahúgát meggyilkolják. A rejtélyes Lisbeth Salander, a tetovált lány, és a tapasztalt újságíró, Mikael Blomkvist összefognak, hogy felderítsék a családi titkokat és az igazság nyomára jussanak. A regény krimi, thriller és társadalmi kritika elemeket ötvöz.'),
(47, 'The Road\r\n', '', 5, 'Thiller/uttttt.jpg', 'The Road\r\n', '2006', 'Cormac McCarthy', 'Iro/Cormac McCarthy.jpg', 'Író', '1933', 'Cormac McCarthy amerikai regényíró, aki irodalmi műveiről, például Az út (The Road) című regényéről és A pusztítás trilógiájáról ismert. \r\nAz erőteljes és sűrű stílusával McCarthy a kortárs amerikai irodalom kiemelkedő alakja.', '\"Az út\" egy posztapokaliptikus regény, mely egy apa és fia utazását követi egy elpusztult világban. A könyv a túlélés, az emberi kapcsolatok és a remény témáit boncolgatja rendkívül súlyos és lélekrenyújtó módon. McCarthy különleges stílusával és atmoszférájával a regény elnyerte a Pulitzer-díjat.'),
(48, 'Treasure Island', '', 5, 'Thiller/kicsessziget.jpg', 'Treasure Island', '1883', 'Robert Louis Stevenson', 'Iro/Robert Louis Stevenson.jpg', 'Író', '1850', 'Robert Louis Stevenson skót író, költő és utazó volt. \r\nLegismertebb művei közé tartozik a Kincses-sziget (Treasure Island), Dr. Jekyll és Mr. Hyde, valamint A fiú, aki tengerész akart lenni (Kidnapped). \r\nStevenson kalandregényeiben gyakran fellelhetők a romantika és a kalandok, amelyek még ma is népszerűek a olvasók körében.', 'Jim Hawkins, a fiatal fiú, egy térképet talál, amely egy eltemetett kincs helyére mutat. A kincsvadászat során izgalmas kalandok veszik kezdetüket, ahol kalózok, csaták és rejtélyek várnak a sziget sötét titkaival.'),
(49, 'Into the Wild', '', 5, 'Thiller/vadon.jpg', 'Into the Wild', '1996', 'Jon Krakauer', 'Iro/Jon Krakauer.jpg', 'Író', '1954', 'Jon Krakauer amerikai író és újságíró, aki kalandregényeiről és dokumentumregényeiről ismert. \r\nAz Alászálló árnyak (Into the Wild) és A levegővéna csúcsa (Into Thin Air) című könyvei világszerte népszerűek.', '\"A vadonba\" Christopher McCandless életét és halálát mutatja be, aki elhagyja a civilizációt, hogy az Alaszkai vadonba meneküljön. Krakauer, aki maga is hegyi mászó volt, részletesen elemzi McCandless döntéseit és azok következményeit, miközben mélyebben feltárja az ember és a természet viszonyát.'),
(50, 'A Kód neve: Villám', '', 5, 'Thiller/zero.jpg', 'A Kód neve: Villám', '2000', 'Ken Follett ', 'Iro/Ken Follett.jpg', 'Író', '1949', 'Ken Follett walesi születésű brit író, aki regényeiről, például A katedrális (The Pillars of the Earth) és A világ két vége (World Without End) című műveiről vált ismert. \r\nFollett történelmi regényeiben a kalandok és az építészeti csodák fontos szerepet játszanak. Jelenlegi információim szerint Ken Follett még él.', 'A regény középpontjában Luke Lucas áll, aki felébred egy washingtoni metrón, de semmire sem emlékszik az előző napokból. Kiderül, hogy Luke egy tehetséges tudós, és azon munkálkodott, hogy egy fontos rakétaindítást segítsen elő. Az események azonban veszélyesen összefonódnak, amikor rájön, hogy a hidegháborús hatalmi harcok és az elágazó szálak sokkal veszélyesebbek, mint gondolta volna.'),
(51, 'Bird Box', '', 6, 'Horror/madarooo.jpg', 'Bird Box', '2014', 'Josh Malerman', 'Iro/Josh Malerman.jpg', 'Író', '1975', 'Josh Malerman amerikai író, aki a pszichológiai horror műfajában tevékenykedik. \r\nAz egyik legismertebb műve a Madarak doboza (Bird Box), amelyet később filmre is adaptáltak. Malerman további regényei között találhatók a „Malorie” és a „Goblin” is.', 'Ezzel a robbanásszerű sikereket arató könyvvel indítjuk el új könyvsorozatunkat, amely Fumax Thriller néven fut majd. A Bird Box tavaly jelent meg, már több mint 15 országban eladták a kiadási jogait, a filmjogok is egyből elkeltek, és az elkészült forgatókönyv meg is nyerte az olyan forgatókönyvek számára kitalált díjat 2014-ben, amelyikből még nem készült film. Nemrég jelölték a patinás Bram Stoker-díjra, aminek megnyerésére nagyon jelentős esélye van. Valami rémisztő dolog garázdálkodik odakint, amire nem szabad ránézni. Egyetlen pillantás elég ahhoz, hogy az ember őrült, kegyetlen gyilkossá váljon. Senki sem tudja, mi az, és honnan jött. A szörnyűséges hírek egyre gyakoribbá válnak. Majd a tévé elsötétül, a rádió elhallgat, és az internet is összeomlik. A telefonok elnémulnak. Az ablakon pedig nem lehet kinézni többé. Mára csak maréknyi túlélő maradt, köztük Malorie két gyermekével, akiket az egyetlen lehetséges módon nevel: a négy fal között. A folyóparti, elhagyatott ház ajtaja zárva, a függönyök behúzva, az ablakokra matracok szögelve. Egyetlen esélyük, hogy elmenekülnek egy másik helyre, ahol talán biztonságban lehetnek. De az előttük álló út elrettentő: harminc kilométer a folyón, egy evezős csónakban bekötött szemmel! Csak Malorie találékonyságára és a gyerekek éles hallására támaszkodhatnak. Egyetlen rossz döntés is végzetessé válhat. És valami követi őket. De vajon ember, állat vagy szörnyeteg? Josh Malerman lélegzetelállító debütálása egy letehetetlen, rémisztő és lebilincselő panoráma egy sarkaiból kifordult világról'),
(52, 'The Dracula', '', 6, 'Horror/vampir.jpg', 'The Dracula', '1897', 'Bram Stoker', 'Iro/Bram Stoker.png', 'Író', '1847', 'Bram Stoker ír író, aki legismertebb műve a Drakula. Stoker az írói pályafutásán kívül színházi menedzser és kritikus is volt. \r\nDrakula, a vámpíros regény, amelyet 1897-ben jelent meg, azóta is a horrorirodalom kiemelkedő alkotásai közé tartozik.', 'Bram Stoker ikonikus regénye az eredeti vámpír, Dracula, köré szőtt sötét és misztikus történetet meséli el. A könyv az angol ügyvéd, Jonathan Harker naplóbejegyzéseiből, levélváltásaiból és más karakterek naplóiból épül fel. Dracula, a kárpát-medencei vámpír, Londonba utazik, és egy veszélyes, véres játékot kezd a védelmét kereső emberekkel.'),
(53, 'The Exorcis', '', 6, 'Horror/exorcist.jpg', 'The Exorcis', '1971', 'Bram Stoker', 'Iro/William Peter Blatty.jpg', 'Író', '1928', 'William Peter Blatty az amerikai író, forgatókönyvíró és filmrendező, aki leginkább a Rémkiváltó (The Exorcist) című horrorregényéről ismert. \r\nA művet később ugyanazon címmel filmre is adaptálták, és a mű nagy hatással volt a horror műfajára.', '\"Az Ördögűző\" egy ijesztő és misztikus regény, amely egy kislányról szól, akit egy démon száll meg, és a családja kétségbeesetten próbálja megmenteni tőle. A regény az exorcizmus témáját járja körül és mélyen beleveti az olvasót az istenhit és a démoni erők konfliktusába.'),
(54, 'Frankenstein', '', 6, 'Horror/frankensten.jpg', 'Frankenstein', '1818', 'Mary Shelley', 'Iro/Mary Shelley.jpg', 'Író', '1797', 'Mary Shelley angol író, aki az egyik első és legismertebb sci-fi regény, a Frankenstein, avagy a modern Prométheusz (Frankenstein; or, The Modern Prometheus) szerzője. \r\nA regényt 1818-ban publikálták, és azóta is az irodalom egyik kiemelkedő alkotásaként tartják számon.', 'Mary Shelley \"Frankenstein\" című regénye a modern horrorirodalom alapkövévé vált. A történet Viktor Frankensteinről szól, aki teremtményt hoz létre, de gyorsan rádöbben, hogy az általa teremtett lény nem az a tökéletes lélek, amit elképzelt. A regény a tudomány és etika, a teremtés és elutasítás, az egyén és társadalom összefonódó témáit érinti.'),
(55, 'The Haunting of Hill House', '', 6, 'Horror/hauning.jpg', 'The Haunting of Hill House', '1959', 'Shirley Jackson', 'Iro/Shirley Jackson.jpg', 'Író', '1916', 'Shirley Jackson amerikai író, aki pszichológiailag mély és sötét témájú műveiről ismert. \r\nAz egyik legismertebb műve Az éjszaka szelleme (The Haunting of Hill House), valamint a Rózsaszínű lovak (The Lottery) című novellája.', 'Shirley Jackson pszichológiai horror regénye egy családról szól, akik egy régi és elhagyott kísértetjárta házban próbálnak éjszakát tölteni.'),
(56, 'It (Az)', '', 6, 'Horror/bohoc.jpg', 'It (Az)', '2017', 'Stephen King', 'Iro/Stephen King.jpg', 'Író', '1947', 'Stephen King az egyik legismertebb és legsikeresebb amerikai horror, fantasy és sci-fi író. \r\nKiemelkedő művei közé tartozik Az (It), A ragyogás (The Shining), a Carrie, a Christine, a Nyári éjszakák réme (The Stand), és számos más bestseller.', 'Heten voltak. Hét kiskamasz barát, akiknek szembe kellett szállniuk a városukat terrorizáló rémmel. A csatornákban, a lefolyókban, a kanálisban lakó Az időről időre felszínre bukkant, és akkor útját hullák szegélyezték. Sok hulla. De Derry városában ezen senki sem lepődött meg. Az emberek halandóak, a gyerekek meg főleg. Egészen addig, amíg ők heten össze nem fogtak, hogy legyőzzék Azt. Bill, a vezér, aki az öccse halálát akarja megbosszulni. Ben, akinek a könyvek a barátai, na meg az ennivaló. Richie, akinek mindig rosszkor jár a szája, ráadásul különféle Hangokon. Stan, aki gyűlöli a rendetlenséget és a piszkot. Eddie, akinek asztmája van és tankszerű anyja. Michael, a néger. És Beverly, a lány, akit ver az apja és akibe ketten is szerelmesek. De hogyan szállhat szembe hét gyerek az egész várost megfertőző gonosszal? Stephen King hatalmas regénye vérfagyasztó izgalmak során válaszolja meg a kérdést. És mesél még gyerekkorról és felnőttségről, pénzről és szegénységről, barátságról és kirekesztettségről, lányról és fiúról. Szóval az életről.'),
(57, 'Psycho', '', 6, 'Horror/psycho.jpg', 'Psycho', '1959', 'Robert Bloch', 'Iro/Robert Bloch.jpg', 'Író', '1917', 'Robert Bloch amerikai író, aki elsősorban horror, sci-fi és krimi műfajokban alkotott. \r\nA legismertebb művei közé tartozik a Psycho, amelyet Alfred Hitchcock filmre is vitett. Bloch jelentős hatással volt a horrorirodalomra, és számos novellát és regényt írt.', 'Robert Bloch pszichológiai thrillerje, \"Psycho,\" a fiatal nő, Marion Crane és a rejtélyes szálloda tulajdonosa, Norman Bates közötti feszültséget és pszichopatológiai elemeket feszegeti. A regény Hitchcock azonos című filmjéhez inspirációt nyújtott.');
INSERT INTO `konyvek` (`id`, `oldal_title`, `oldal_video`, `kategoria_id`, `konyv_kep`, `konyv_cim`, `konyv_kiadas`, `iro_nev`, `iro_kep`, `iro_foglalkozas`, `iro_szuletett`, `iro_leiras`, `konyv_leiras`) VALUES
(58, 'The Ritual', '', 6, 'Horror/rituale.jpg', 'The Ritual', '2011', 'Adam Nevill', 'Iro/Adam Nevill.jpg', 'Író', '1969', 'Adam Nevill angol író, aki elsősorban horror és thriller műfajokban tevékenykedik. Művei között található a The Ritual, ami később filmet is kapott. \r\nNevill munkái sötét atmoszférájáról és karakterfejlődéseiről ismertek.', 'Négy régi egyetemi barát újra találkozik egy túrára az Északi-sarkkör skandináv vadonjában. Már nem fiatal férfiak, kevés közös vonásuk maradt, és a feszültség növekszik, ahogy küzdenek a kapcsolódásért. Frusztráltan és fáradtan egy rövidebb utat választanak, amely túrájukat rémálommá változtatja, amely az életükbe kerülhet.\r\nElveszetten, éhesen és évezredek óta érintetlen erdővel körülvéve egy elszigetelt régi házba botlanak. Belül régi rítusok és pogány áldozatok hátborzongató maradványait találják'),
(59, 'The Shining', '', 6, 'Horror/shining.jpg', 'The Shining', '1977', 'Stephen King ', 'Iro/Stephen King.jpg', 'Író', '1947', 'Stephen King az egyik legismertebb és legsikeresebb amerikai horror, fantasy és sci-fi író. \r\nKiemelkedő művei közé tartozik Az (It), A ragyogás (The Shining), a Carrie, a Christine, a Nyári éjszakák réme (The Stand), és számos más bestseller.', 'Stephen King egyik ikonikus műve, \"The Shining\" egy rémisztő szállodában játszódik, ahol a Jack Torrance nevű író és családja szembesül egy rejtélyes és sötét múlttal. A szálloda elszigetelt helye és a Jack elméjében zajló fokozatos leépülés együttesen teremtenek egy ijesztő és különleges atmoszférát.'),
(60, 'The Silence of the Lambs', '', 6, 'Horror/valamibarany.jpg', 'The Silence of the Lambs', '1988', 'Thomas Harris', 'Iro/Thomas Harris.jpg', 'Író', '1940', 'Thomas Harris amerikai író, aki krimi- és horrorregényeiről ismert. \r\nLeghíresebb műve a Néma bárányok (The Silence of the Lambs), amelyet később filmes adaptáció is követett. \r\nHannibal Lecter karaktere, akit Harris alkotott meg, az irodalom egyik leghírhedtebb gonosztevője.', 'Thomas Harris kultikus regénye, \"The Silence of the Lambs,\" az FBI ügynöke, Clarice Starling, és a börtönből megszökött szociopata orvos, Hannibal Lecter közötti különleges kapcsolatot követi. Clarice-nak Lecter segítségére van szüksége egy másik szörnyű sorozatgyilkos elfogásához. A regény komplex karaktereket, intenzív pszichológiai elemeket és feszült atmoszférát kínál.'),
(61, 'City of Lions', '', 7, 'Krimi/oroszlan.jpg', 'City of Lions', '2017', 'HJ. Torres', 'Iro/Anonym.webp', 'Író', '-', 'A „The Black Butterfly: Mercedes M. Dance” című művéért vált ismertté, ami a leszbikus irodalom egyik meghatározó alkotása.', 'Egy fiatal nő élete veszélybe kerül a város sötét alvilágában, és egy titkos szervezet elleni küzdelme a regény középpontjában áll'),
(62, 'A Little Life', '', 7, 'Krimi/kiselet.jpg', 'A Little Life', '2015', 'Hanya Yanagihara', 'Iro/Hanya Yanagihara.jpg', 'Író', '1974', 'Hanya Yanagihara egy élő amerikai író és újságíró, aki a The People in the Trees című regényéről és különböző kiemelkedő újságírói munkáiról ismert.', 'Bár ez a regény több műfajban is otthonosan mozog, a krimi elemek is jelen vannak ebben a megrázó és intenzív történetben négy barát életéről.'),
(63, 'The Truth of the Matter', '', 7, 'Krimi/igazsag.jpg', 'The Truth of the Matter', '2011', 'Robb Forman Dew', 'Iro/Robb Forman Dew.webp', 'Író', '1946', 'Robb Forman Dew amerikai író, aki a The Family Heart: A Memoir of When Our Son Came Out című könyvéért kapta meg a 1994-es National Book Awardot. \r\nRegényei és esszéi gyakran az élet nehézségeivel és a családi kapcsolatokkal foglalkoznak.', 'Egy kisvárosi ügyész életét és karrierjét követjük ebben a könyvben, miközben próbálja felderíteni egy tragikus esemény hátterét.'),
(64, 'In the Name of the Family', '', 7, 'Krimi/csalad.jpg', 'In the Name of the Family', '2017', 'Sarah Dunant', 'Iro/Sarah Dunant.jpg', 'Író', '1950', 'Sarah Dunant angol író és történész. Elsősorban történelmi regények szerzőjeként ismert, például a „The Birth of Venus” és a „In the Company of the Courtesan”.', 'Egy történelmi krimi, amely a reneszánsz Itáliában játszódik, és a Borgia család és Michelangelo életébe enged bepillantást.'),
(65, 'The Invisible Life of Addie LaRue', '', 7, 'Krimi/lathatatlanelet.jpeg', 'The Invisible Life of Addie LaRue', '2020', 'V. E. Schwab', 'Iro/Victoria Schwab.jpg', 'Író', '1987', 'V. E. Schwab (eredeti nevén Victoria Schwab) amerikai fantasy és sci-fi író, aki a Shades of Magic trilógia (A Darker Shade of Magic) és a Vicious című regény szerzője. \r\nSchwab sikeresen alkot mind ifjúsági, mind felnőtt olvasóknak szóló műveket.', 'Habár ez fantasy elemeket is tartalmaz, a regény egy nő életét követi, aki egyezséget köt egy sötét erővel, és ezzel láthatatlanná válik mindenki számára.'),
(66, 'Az év könyvesboltja', '', 7, 'Krimi/azevkonyvesboltja.jpeg', 'Az év könyvesboltja', '2014', 'Gabrielle Zevin', 'Iro/Gabrielle Zevin.jpg', 'Író', '1977', 'Gabrielle Zevin amerikai író és forgatókönyvíró. Legismertebb művei közé tartozik a „The Storied Life of A.J. Fikry” című regény, ami könyvszeretetről és könyvkereskedésről szól.', 'Egy könyvkereskedő története, aki különös könyvekkel találja szembe magát, és azokon keresztül alakul át az élete.'),
(67, 'The Child', '', 7, 'Krimi/gyerek.jpg', 'The Child', '2017', 'Fiona Barton', 'Iro/Fiona Barton.jpg', 'Író', '1959', 'Fiona Barton angol újságíró és író. A pszichológiai thriller műfajában alkot, és több sikeres könyvet írt, például a „The Widow” és a „The Child”.', 'Egy újságíró nyomozása egy régi gyermekgyilkosság ügyében, ami kapcsolatban lehet az egyik városi ház felújításával.'),
(68, 'The Last Child on the Mountain', '', 7, 'Krimi/utolsogyerek.jpg', 'The Last Child on the Mountain', '2010', 'John Hart', 'Iro/John Hart.jpg', 'Író', '1988', 'John Hart egy élő amerikai író, aki a thriller műfajában tevékenykedik. \r\nLegismertebb művei közé tartozik a „Down River”, a „The Last Child” és a „Redemption Road”. \r\nHart többszörös díjnyertes szerző', 'Egy fiú eltűnése és egy testvérének kitartó kutatása a regény fő cselekménye, amely egy kisváros rejtélyes eseményeibe vezet be'),
(69, 'The Last Time I Lied', '', 7, 'Krimi/hazug.jpg', 'The Last Time I Lied', '2018', 'Riley Sage', 'Iro/Riley Sager.jpg', 'Író', '-', 'Riley Sager a „Final Girls” és a „The Last Time I Lied” című pszichológiai thriller regények mögött álló írói álnév.', 'Egy nő visszatér egy gyerekkori nyári táborba, ahol évekkel korábban eltűnt egy táborlány, és most megpróbálja kideríteni az igazságot.'),
(70, 'The Waves', '', 7, 'Krimi/hullam.jpg', 'The Waves', '2011', 'Virginia Woolf', 'Iro/Virginia Woolf.jpg', 'Író', '1882', 'Virginia Woolf angol író, modernista irodalmi mozgalom kiemelkedő alakja. Művei közé tartozik a „Mrs Dalloway”, a „To the Lighthouse” és az „Orlando”. \r\nWoolf a pszichológia és az időbeni folyamatok mély elemzésével vált ismertté irodalmi körökben. Saját tragikus sorsáról ismert, és 1941-ben öngyilkos lett.', 'Ez a regény Virginia Woolf egyik késői műve, amelyben öt karakter szemszögéből követhetjük nyomon az életüket.'),
(71, 'A szőke ciklon', '', 8, 'Humor/szoke.jpg', 'A szőke ciklon', '1939', 'Rejtő Jenő', 'Iro/Rejto.jpg', 'Író', '1905', 'Rejtő Jenő magyar író, aki elsősorban humoros krimikről és kalandregényekről ismert. \r\nŐ volt a legismertebb írói álnevei között Chic, Pitt és mások. Rejtő Jenő tragikus körülmények között, egy repülőbalesetben vesztette életét a második világháború alatt.', 'Jim Hogan, az életfogytiglanra ítélt dartmoori fegyenc végrendeletében egymillió font sterling értékű, dió nagyságú gyémántot hagyományoz Miss Emily Westonra, az ifjú londoni bölcsészhallgatóra, aki egyetlen látogatója volt börtönévei során Emilynek „csupán” meg kell találnia a tizenöt évvel korábban készült Buddha-szobrocskát, amelyben a gyémánt rejtőzik. Nem lesz nehéz, alig pár darab készült belőle, és mind itt van valahol a Földön. A végrendelet tartalmát azonban mások is megismerték…'),
(72, 'Család A Dombon', '', 8, 'Humor/csalad.jpg', 'Család A Dombon', '2022', 'Patak Gyöngyvér', 'Iro/Patak.jpg', 'Író', '-', '\"A célom, hogy támogassak és kulcsokat adjak, de ugyanilyen fontos, hogy szórakoztassak. Biztosan tudom, hogy vidáman sokkal tisztábban látunk, és könnyebben oldunk meg bármilyen problémát. Meg amúgy is jobb nevetni,,', 'A város egyik legrégebbi lakótelepén kilátástalan az élet – szó szerint és képletesen is –, főleg egy kisbabával, és Gyömbi úgy érzi, nem maradhatnak itt tovább. Nagy családra vágyik, hatalmas álmai vannak, és ehhez levegőre van szüksége. A szomszédos falu, ahova kis családjával elmenekül, békét és nyugalmat ígér, ám hamar kiderül, hogy ahol férfiak és gyerekek élnek – utóbbiból ráadásul egyre több –, ott minden van, csak béke és nyugalom nincs.'),
(73, 'A Csodálatos Világom', '', 8, 'Humor/vilagom.jpg', 'A Csodálatos Világom', '2014', 'Keri Smith', 'Iro/Keri Smith.jpg', 'Író', '1973', 'Keri Smith egy kanadai író, művész és illusztrátor, aki számos interaktív könyvet készített, amelyek segítik az embereket a kreatív gondolkodásban és az alkotásban. A munkásságában fontos szerepet játszanak a naplók és a kreatív kifejezés eszközei. Néhány népszerű könyve közé tartozik a \"Wreck This Journal\", amely arra ösztönzi az olvasókat, hogy szándékosan roncsolják meg a könyvet, és ezzel egyfajta kreatív folyamat részesei legyenek.', 'A ​nemzetközi könyvsiker, a Nyírd ki ezt a naplót alkotójának útmutatója a tökéletes saját világ felépítéséhez.\r\n            A Csodálatos világom című könyvben Keri Smith arra kéri az olvasókat, hogy képzeljenek el valami egészen újat: egy saját maguk által teremtett egyedi világot.\r\n            Az olvasók először is összeállítanak egy listát mindarról, amihez valamiért vonzódnak: dolgokról, amelyeket szeretnek és gyűjtenek, színekről, formákról, ötletekről, emberekről és lényekről, amelyek lenyűgözik őket. A listán szereplő elemek lesznek az ő képzeletbeli világuk építőkövei; ezekkel alapozzák majd meg az új helyet, amelyet idővel elkezdenek belakni. Ezután arra kapnak biztatást, hogy a világukkal kapcsolatban gondolkodjanak el tájról, helynevekről, térképekről, pénznemekről, lakosokról, logókról, ételekről, történetekről és még sok minden másról.'),
(74, 'Dad is fat', '', 8, 'Humor/apu.jpg', 'Dad is fat', '2017', 'Jim Gaffigan', 'Iro/Jim Gaffigan.jpg', 'Író', '1966', 'Jim Gaffigan amerikai stand-up komikus, színész és író.', 'Egy humoros memoár, amelyben a neves stand-up komikus, Jim Gaffigan, szórakoztatóan és öniróniával meséli el tapasztalatait az apaságról, a családi életről és a mindennapi kihívásokról. Gaffigan könyve tele van könnyed humorral és éles megfigyelésekkel a szülői lét vicces és kaotikus pillanatairól.'),
(75, 'Milyen anya az ilyen', '', 8, 'Humor/anya.jpg', 'Milyen anya az ilyen', '2022', 'Spira Eszter Mirjam', 'Iro/Spira Eszter Mirjam.jpg', 'Író', '-', 'Spira Eszter Mirjam magyar költő és író. 10 évesen kezdett el írni, ami a szenvedéllyévé vált', 'Nálatok is minden gyerek első szóra kikel az ágyból, és egy gyors öltözés és reggeli után mosolyogva indul suliba? A szókincsük választékos, és mindig van egy kedves szavuk mindenkihez? Minden napod tökéletes szettekben indítod, vacsorára pedig hat fogásos ételkölteményeket rittyentesz?'),
(77, 'Apu azért iszik mert te sírsz', '', 8, 'Humor/apusir.jpg', 'Apu azért iszik mert te sírsz', '2016', 'Puzsér Róbert', 'Iro/Puzser.jpg', 'Író', '1974', 'Puzsér Róbert élő magyar publicista, író és műsorvezető', 'Egy mély és érzelmekkel teli regény, amely egy apa és lánya kapcsolatának nehézségeit és a családi dinamika mélységeit járja körül. A történetben az alkoholizmus és az érzelmi kihívások mellett az összetartozás és a gyógyulás is központi szerepet kapnak. Egy érzékeny és tanulságos olvasmány a családi kapcsolatok bonyolult világáról.'),
(78, 'Soma a beszélő kutya', '', 8, 'Humor/soma.jpg', 'Soma a beszélő kutya', '2022', 'Majtényi László', 'Iro/Laszlo.jpg', 'Író', '1963', 'Majtényi László magyar jogász, író és politikus.', 'Posztjait több ezren követik, osztják és lájkolják: a Balaton-felvidéken és Budapesten már sokan felismerik, igazi celeb lett. Büszkén adjuk hát közre a beszélő (és író) kutya történeteit, melyek kutya–ember, kutya–kutya és kutya–egyéb állat viszonyokról, barátságról, hűségről, állítólagos vagyon elleni bűncselekményekről (konkrétan: kolbász, sajt, sültek stb.), különféle jogokról és kötelmekről szólnak. Soma, bár nem végzett jogász, mégis tűéles fogakkal harapja ketté a jogfilozófia több gordiuszi csomóját is, amelyeken a kétlábúak évezredek óta csak nyammognak, szerencsétlenkedve.'),
(79, 'Prince and the Program', '', 8, 'Humor/herceg.jpg', 'Prince and the Program', '2015', 'Aldous Mercer', 'Iro/Anonym.webp', 'Író', '-', 'Aldous Mercer egy író, aki romantikus és fantasy műfajokban alkot.', 'Mordred Pendragon, a Kárhozott Herceg, megint valami rosszat tett. Hét évig Kanadába száműzték, ahol munkát kell találnia a számlái kifizetéséhez. Olyan okokból, amelyeket nem hajlandó felfedni, Mordred úgy dönt, hogy \"Szoftvertervező\" szép szóviccnek hangzik. És bár a \"Egyszer és Mindörökké Király megölése, az én apám\" és \"az az idő a feudális Japánban\" tapasztalata nem túl előnyös önéletrajzi anyagként, egy kis torontói tech kezdőnél feladják neki a lehetőséget.'),
(80, '18 Randi', '', 8, 'Humor/18randi.jpg', '18 Randi', '2017', 'Gecse Dóra ', 'Iro/Gecse.jpg', 'Író', '-', 'Gecse Dóra egy magyar író és újságíró.', 'Mindenhol ​száraz zsírcseppek, kávéfolt, kiszáradt teafilterek és az elmaradhatatlan morzsa. A tűzhelyen egy serpenyő. A benne hagyott hideg zsírban szépen kirajzolódott egy nagy szál kolbász helye. Utálok takarítani, de esküszöm, kedvem támadt hozzá. Sikítozni KELL. Remélem, minden nő megjegyezte!'),
(81, 'The Sweet Revenge of Celia Door', '', 8, 'Humor/bosszu.jpg', 'The Sweet Revenge of Celia Door', '2014', 'Karen Finneyfrock ', 'Iro/Karen Finneyfrock.jpg', 'Író', '-', 'Karen Finneyfrock egy amerikai költő és író', 'Karen Finneyfrock egy lenyűgöző költő, így nem meglepő, hogy első regénye is költői. Emellett vicces, izgalmas, és olyan fájdalmas, mint bárki tinédzser évei. Olvasd el, kérlek.\"\r\nSherman Alexie, a The Absolutely True Diary of a Part-Time Indian című könyv National Book Award-díjas szerzője.'),
(82, 'A vow so bold and deadly', '', 9, 'Ifjusagi/bold.jpg', 'A vow so bold and deadly', '2023', 'Brigid Kemmerer', 'Iro/Brigid Kemmerer.jpg', 'Író', '1978', 'Brigid Kemmerer egy amerikai író, aki ifjúsági és fantasztikus irodalmat is alkot. \r\nA „Cursebreakers” és a „Elemental” sorozatok ismertek tőle.<', 'A lenyűgöző Átoktörő-sorozat befejező része.\r\n            Nézz szembe a félelmeiddel, vívd meg a csatát! Emberfall rohamosan pusztul, és a végletekig megosztott: vannak, akik úgy vélik, a trón Rhent illeti, ám mások alig várják, hogy új korszak kezdődjön Grey, a jogos örökös vezetésével. Grey két hónap türelmi időt adott Emberfallnak a támadás előtt, ám ez idő alatt Rhen mindenkitől elfordult, még Harpertől is, aki kétségbeesetten próbál segíteni neki, hogy megtalálja a békéhez vezető utat. Vívd meg a csatát, mentsd meg a királyságot! Eközben Lia Mara azért küzd, hogy anyjánál emberségesebben uralkodjon Syhl Shallow felett. Miután a mágusokat kiűzték az országból, évtizedekig tartó békés időszak köszöntött be, ám az alattvalók közül nem mindenki nézi jó szemmel, hogy Lia Mara egy varázserővel bíró herceggel és egy aparóval szövetkezik. A háború közeledtével Lia Mara elbizonytalanodik: valóban ő az a királynő, akire az országának szüksége van? A két birodalom egyre közelebb sodródik a fegyveres összecsapáshoz, ami próbára teszi a hűséget, szerelmeket sodor veszélybe, egy régi ellenség újbóli felbukkanása pedig mindenkire fenyegetést jelent.'),
(83, 'The Divergent', '', 9, 'Ifjusagi/valami.jpg', 'The Divergent', '2011', 'Veronica Roth', 'Iro/Veronica Roth.jpeg', 'Író', '1988', 'Veronica Roth egy amerikai író, aki a „Divergent” trilógia szerzőjeként vált ismert. A fiataloknak szánt irodalomban, különösen a dystópikus műfajban, szerzett hírnevet. \r\nVeronica Roth jelenleg él és aktív íróként működik.', 'A történet egy jövőbeli, poszt-apokaliptikus Chicagóban játszódik, ahol a társadalom öt frakcióra oszlik, attól függően, melyik érték a legfontosabb az egyénnek: az őszinteség, az önfeláldozás, a bölcsesség, a becsület vagy a bátorság. A főszereplő, Beatrice \"Tris\" Prior egy olyan csoportba, a Bátorokba tartozik, de kiderül, hogy ő \"divergens\", vagyis nem illeszkedik egyetlen frakcióhoz sem. A divergens emberek veszélyesek a társadalomra nézve, és Trisnek el kell rejtenie valódi identitását. A regény izgalmas, tele van kalanddal, intrikával és az egyéni identitás keresésével a társadalom által előírt normák között.'),
(84, 'Az éhezők viadala', '', 9, 'Ifjusagi/ehezok.jpg', 'Az éhezők viadala', '2008', 'Suzanne Collins', 'Iro/Suzanne Collins.jpg', 'Író', '1962', 'Suzanne Collins egy amerikai író, aki leginkább a Vadvirág (The Hunger Games) trilógia szerzőjeként ismert. \r\nA regényei a fiataloknak szánt irodalom jelentős sikereket értek el és filmes adaptációkat is kaptak. Suzanne Collins jelenleg él és aktív író.', 'A történet egy poszt-apokaliptikus világban játszódik, ahol a Capitol elnyomja a tizenkét körzettel rendelkező országot. A körzeteket minden évben egy fiú és egy lány kiválasztásával küldik be az Éhezők Viadalába, egy televíziós eseménybe, ahol a résztvevőknek meg kell küzdeniük egymással, mígnem csak egy marad életben. A történet középpontjában Katniss Everdeen áll, aki önkénteskedik testvére helyett a Viadalban való részvételre. A regény során Katnissnek meg kell küzdenie nemcsak a túléléseért, hanem a forradalom szikrájának is kezdetét jelentő eseményekkel.'),
(85, 'Jók és Rosszak iskolája', '', 9, 'Ifjusagi/jok.jpg', 'Jók és Rosszak iskolája', '2020', 'Soman Chainani', 'Iro/Soman Chainani.jpg', 'Író', '1989', 'Soman Chainani egy amerikai író és rendező. Legismertebb műve a „The School for Good and Evil” trilógia, amely ifjúsági fantasy és meseelemeket tartalmaz.', 'Ősidőknek erdejében Két kastély áll, fej fej mellett; Egy a Jónak, egy Gonosznak, Együtt, de mind mást tanulnak. Menekülnél, de nem lehet, Kifelé csak mese vezet.\"Gavaldon legszebb lánya, Sophie egész eddigi életében titkon arról ábrándozott, hogy elrabolják, és elviszik egy elvarázsolt világba. Rózsaszín ruhákban, fess topánkákban jár. Rajong a jó cselekedetekért, ezért egészen biztos abban, hogy nagyon jó jegyeket kapna a Jók Tagozatán, és dicséretes mesekönyv-hercegnő bizonyítványa lehetne. Agatha viszont mindig formátlan, fekete hacukákban jár, gonosz macskája van, és szinte mindenkit utál, ezért természetesnek látszik, hogy ő a Rosszak Tagozatára kerül.Amikor azonban a két lány a Végtelen Erdőbe kerül, azt tapasztalják, hogy sorsuk a remélttel éppen ellentétesen alakul, és hamar rájönnek, hogy egy tündérmeséből a leggyorsabb kivezető út az, ha... túlélik.'),
(86, 'A Szolgálólány meséje', '', 9, 'Ifjusagi/szolgalo lany.jpg', 'A Szolgálólány meséje', '1985', 'Margaret Atwood', 'Iro/Margaret Atwood.jpg', 'Író', '1939', 'Margaret Atwood kanadai író, költő és kritikus. Legismertebb művei közé tartozik az „A szolgálólány meséje” (The Handmaid\'s Tale) és az „Oryx and Crake”. \r\nAtwood sok díjat és elismerést kapott évtizedes írói karrierje során.', 'A regény egy alternatív jövőben játszódik, ahol egy totalitárius társadalom, Gilead, alakul ki az Egyesült Államokban. A történet főszereplője, Offred, egy szolgálólány, aki a rendszerben kiszolgáltatott helyzetben találja magát. A Gileadot egy vallási diktatúra irányítja, és a nők szerepe kizárólag a szaporodásra korlátozódik. A regény a nők jogai, az egyéni szabadság és a hatalommal való visszaélés témáit feszegeti, és mélyen elgondolkodtató képet fest egy elnyomó társadalomról.'),
(87, 'Mielőtt megismertelek', '', 9, 'Ifjusagi/mielott.jpg', 'Mielőtt megismertelek', '2012', 'Jojo Moyes', 'Iro/Jojo Moyes.jpg', 'Író', '1969', 'Jojo Moyes egy brit író, aki különböző műfajokban alkot, beleértve a romantikus regényeket és a drámákat is. \r\nAz egyik legsikeresebb műve a „Me Before You” című regény, ami később filmet is kapott.', 'A regény középpontjában Louisa Clark áll, egy fiatal nő, aki elveszíti az állását, majd váratlanul egy gazdag, de testileg sérült férfi, Will Traynor gondozójaként kap munkát. Will korábban sportos, aktív életet élt, de egy baleset következtében bénult, és most az életminőségét veszélyezteti. A történet során kibontakozik Louisa és Will közötti különleges kapcsolat, ahogy Louisa igyekszik megváltoztatni Will nézeteit az életről és a boldogságról. A regény érzelmekkel teli és mély gondolatokat ébreszt a szeretetről és az élet értelméről.'),
(88, 'Az Olimposziak', '', 9, 'Ifjusagi/isten.jpg', 'Az Olimposziak', '2005', 'Rick Riordan', 'Iro/Rick Riordan.jpg', 'Író', '1964', 'Rick Riordan egy amerikai író, aki leginkább az ifjúsági fantasztikus irodalom terén vált ismertté. \r\nLeghíresebb művei közé tartozik a Percy Jackson & az Olimposziak sorozat, amin túl írt más mitológiai alapokon nyugvó könyveket is.', 'Ez egy fantasy-sorozat első kötete, melynek főszereplője Percy Jackson, egy fiú, aki rájön, hogy félvér, azaz apja egy görög isten. Percy-t a Viharok Ura, Zeusz vádolja meg egy elveszett villám miatt, és ezért Percynek el kell indulnia az Olimposzra, hogy bebizonyítsa ártatlanságát és megakadályozza, hogy a háború kitörjön az istenek között. A történet során Percy barátokra talál, és kiderül, hogy az Olimposz és a görög mitológia valóságosan létezik a modern világban. A könyv humorral, kalanddal és mitológiai elemekkel van teli.'),
(89, 'Red with royal blue', '', 9, 'Ifjusagi/voros.webp', 'Red with royal blue', '2019', 'Casey McQuiston', 'Iro/Casey McQuiston.jpg', 'Író', '1991', 'Casey McQuiston egy élő amerikai író, aki a romantikus és LGBTQ+ műfajokban alkot.', 'A regény egy alternatív világban játszódik, ahol az Amerikai Egyesült Államok elnökének fia, Alex Claremont-Diaz és a brit herceg, Henry Fox-Mountchristen ellenségek. Azonban egy kínos esemény után a két fiatalembernek hamarosan szembesülniük kell a saját érzéseikkel és a világ elvárásaival szemben. A történet egy romantikus komédia, amely humorral és érzelmekkel mutatja be a két fiatal és különleges kapcsolatát, miközben egy alternatív valóságban játszódik, ahol az LGBT+ témák is fontos szerepet kapnak.'),
(90, 'Tűzpróba', '', 9, 'Ifjusagi/tuz.jpg', 'Tűzpróba', '2009', 'James Dashner', 'Iro/James Dashner.jpg', 'Író', '1972', 'James Dashner egy amerikai író, aki legismertebb a „The Maze Runner” trilógia szerzőjeként. \r\nDashner ifjúsági és sci-fi műfajokban alkot, és számos bestsellerrel büszkélkedhet.', 'Ez a regény egy sci-fi kalandregény, melyben egy fiatal srác, Thomas, egy nap egy lifttel ébred egy labirintusban, és elveszti az emlékeit. A labirintuson kívül egy csoport fiatal próbál túlélni és megtudni, miért vannak zárványban. A történet kibontakozásával kiderül, hogy Thomasnak és társainak fontos szerepe van egy titokzatos és veszélyes kísérletben. A regény izgalmas és fordulatos, és a főszereplőknek számos kihívással kell szembenézniük a túlélés és az igazság felfedezése érdekében.'),
(91, 'Vőrős Királynő', '', 9, 'Ifjusagi/Kiralyno.webp', 'Vőrős Királynő', '2015', 'Victoria Aveyard', 'Iro/Victoria Aveyard.jpg', 'Író', '1990', 'Victoria Aveyard egy amerikai író, aki a „Red Queen” sorozatáról vált ismert. Az ifjúsági fantasztikus irodalomban aktív és sikeres szerző.', 'A történet egy világban játszódik, ahol a társadalomot a vér színe határozza meg: a vörös vérűek az alsóbbrendűek, míg az ezüst vérűek kivételezettek, mágikus képességekkel rendelkeznek. A főszereplő, Mare Barrow, egy vörös vérű lány, de váratlanul felfedez egy sajátos erejét, ami a királyi család figyelmét is felkelti. A regény tele van politikai intrikával, árulással és a hatalom körül kialakuló konfliktusokkal. Mare kénytelen belekerülni az ezüst vérűek világába, és a történet folyamán megkérdőjelezi a társadalmi rendszer igazságosságát és az egyenlőtlenségeket.');

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `konyvkategoria`
--

CREATE TABLE `konyvkategoria` (
  `id` int(11) NOT NULL,
  `nev` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

--
-- A tábla adatainak kiíratása `konyvkategoria`
--

INSERT INTO `konyvkategoria` (`id`, `nev`) VALUES
(1, 'Képergény'),
(2, 'Fantasy'),
(3, 'Erotika'),
(4, 'Romantika'),
(5, 'Thriller'),
(6, 'Horror'),
(7, 'Krimi'),
(8, 'Humor'),
(9, 'Ifjúsági');

--
-- Indexek a kiírt táblákhoz
--

--
-- A tábla indexei `chat`
--
ALTER TABLE `chat`
  ADD PRIMARY KEY (`id`),
  ADD KEY `felhasznalo_id` (`felhasznalo_id`),
  ADD KEY `kategoria_id` (`kategoria_id`);

--
-- A tábla indexei `felhasznalok`
--
ALTER TABLE `felhasznalok`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `Email_unique` (`id`),
  ADD UNIQUE KEY `felhasznalonev_unique` (`id`);

--
-- A tábla indexei `hozzaszolasok`
--
ALTER TABLE `hozzaszolasok`
  ADD PRIMARY KEY (`id`),
  ADD KEY `felhasznalo_id` (`felhasznalo_id`),
  ADD KEY `konyv_id` (`konyv_id`);

--
-- A tábla indexei `kedvelesek`
--
ALTER TABLE `kedvelesek`
  ADD PRIMARY KEY (`id`),
  ADD KEY `felhasznalo_id` (`felhasznalo_id`),
  ADD KEY `konyv_id` (`konyv_id`);

--
-- A tábla indexei `konyvek`
--
ALTER TABLE `konyvek`
  ADD PRIMARY KEY (`id`),
  ADD KEY `kategoria_id` (`kategoria_id`);

--
-- A tábla indexei `konyvkategoria`
--
ALTER TABLE `konyvkategoria`
  ADD PRIMARY KEY (`id`);

--
-- A kiírt táblák AUTO_INCREMENT értéke
--

--
-- AUTO_INCREMENT a táblához `chat`
--
ALTER TABLE `chat`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

--
-- AUTO_INCREMENT a táblához `felhasznalok`
--
ALTER TABLE `felhasznalok`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

--
-- AUTO_INCREMENT a táblához `hozzaszolasok`
--
ALTER TABLE `hozzaszolasok`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=36;

--
-- AUTO_INCREMENT a táblához `kedvelesek`
--
ALTER TABLE `kedvelesek`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- AUTO_INCREMENT a táblához `konyvek`
--
ALTER TABLE `konyvek`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=92;

--
-- AUTO_INCREMENT a táblához `konyvkategoria`
--
ALTER TABLE `konyvkategoria`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

--
-- Megkötések a kiírt táblákhoz
--

--
-- Megkötések a táblához `chat`
--
ALTER TABLE `chat`
  ADD CONSTRAINT `chat_ibfk_1` FOREIGN KEY (`felhasznalo_id`) REFERENCES `felhasznalok` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Megkötések a táblához `hozzaszolasok`
--
ALTER TABLE `hozzaszolasok`
  ADD CONSTRAINT `hozzaszolasok_ibfk_1` FOREIGN KEY (`konyv_id`) REFERENCES `konyvek` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Megkötések a táblához `kedvelesek`
--
ALTER TABLE `kedvelesek`
  ADD CONSTRAINT `kedvelesek_ibfk_1` FOREIGN KEY (`konyv_id`) REFERENCES `konyvek` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Megkötések a táblához `konyvek`
--
ALTER TABLE `konyvek`
  ADD CONSTRAINT `konyvek_ibfk_1` FOREIGN KEY (`kategoria_id`) REFERENCES `konyvkategoria` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
